# Generated by Django 2.2.12 on 2020-04-12 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitNum', models.CharField(max_length=6)),
                ('bed', models.DecimalField(decimal_places=1, max_digits=2)),
                ('bath', models.DecimalField(decimal_places=1, max_digits=2)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_address', to='properties.Address')),
            ],
        ),
    ]
